// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/payment/payment_service.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_payment_payment_service_proto protoreflect.FileDescriptor

const file_proto_payment_payment_service_proto_rawDesc = "" +
	"\n" +
	"#proto/payment/payment_service.proto\x12\apayment\x1a\x1bproto/payment/payment.proto2\x96\x01\n" +
	"\x0ePaymentService\x12A\n" +
	"\n" +
	"AddPayment\x12\x17.payment.PaymentRequest\x1a\x18.payment.PaymentResponse\"\x00\x12A\n" +
	"\n" +
	"GetPayment\x12\x17.payment.PaymentRequest\x1a\x18.payment.PaymentResponse\"\x00B6Z4github.com/eliezerraj/go-grpc-proto/protogen/paymentb\x06proto3"

var file_proto_payment_payment_service_proto_goTypes = []any{
	(*PaymentRequest)(nil),  // 0: payment.PaymentRequest
	(*PaymentResponse)(nil), // 1: payment.PaymentResponse
}
var file_proto_payment_payment_service_proto_depIdxs = []int32{
	0, // 0: payment.PaymentService.AddPayment:input_type -> payment.PaymentRequest
	0, // 1: payment.PaymentService.GetPayment:input_type -> payment.PaymentRequest
	1, // 2: payment.PaymentService.AddPayment:output_type -> payment.PaymentResponse
	1, // 3: payment.PaymentService.GetPayment:output_type -> payment.PaymentResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_payment_payment_service_proto_init() }
func file_proto_payment_payment_service_proto_init() {
	if File_proto_payment_payment_service_proto != nil {
		return
	}
	file_proto_payment_payment_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_payment_service_proto_rawDesc), len(file_proto_payment_payment_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payment_payment_service_proto_goTypes,
		DependencyIndexes: file_proto_payment_payment_service_proto_depIdxs,
	}.Build()
	File_proto_payment_payment_service_proto = out.File
	file_proto_payment_payment_service_proto_goTypes = nil
	file_proto_payment_payment_service_proto_depIdxs = nil
}
