// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/pod/pod_service.proto

package pod

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_pod_pod_service_proto protoreflect.FileDescriptor

const file_proto_pod_pod_service_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/pod/pod_service.proto\x12\x03pod\x1a\x13proto/pod/pod.proto2;\n" +
	"\n" +
	"PodService\x12-\n" +
	"\x06GetPod\x12\x0f.pod.PodRequest\x1a\x10.pod.PodResponse\"\x00B2Z0github.com/eliezerraj/go-grpc-proto/protogen/podb\x06proto3"

var file_proto_pod_pod_service_proto_goTypes = []any{
	(*PodRequest)(nil),  // 0: pod.PodRequest
	(*PodResponse)(nil), // 1: pod.PodResponse
}
var file_proto_pod_pod_service_proto_depIdxs = []int32{
	0, // 0: pod.PodService.GetPod:input_type -> pod.PodRequest
	1, // 1: pod.PodService.GetPod:output_type -> pod.PodResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pod_pod_service_proto_init() }
func file_proto_pod_pod_service_proto_init() {
	if File_proto_pod_pod_service_proto != nil {
		return
	}
	file_proto_pod_pod_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pod_pod_service_proto_rawDesc), len(file_proto_pod_pod_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pod_pod_service_proto_goTypes,
		DependencyIndexes: file_proto_pod_pod_service_proto_depIdxs,
	}.Build()
	File_proto_pod_pod_service_proto = out.File
	file_proto_pod_pod_service_proto_goTypes = nil
	file_proto_pod_pod_service_proto_depIdxs = nil
}
