// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/health/health_service.proto

package health

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_health_health_service_proto protoreflect.FileDescriptor

const file_proto_health_health_service_proto_rawDesc = "" +
	"\n" +
	"!proto/health/health_service.proto\x12\x06health\x1a\x19proto/health/health.proto2\x8e\x01\n" +
	"\x06Health\x12@\n" +
	"\x05Check\x12\x1a.health.HealthCheckRequest\x1a\x1b.health.HealthCheckResponse\x12B\n" +
	"\x05Watch\x12\x1a.health.HealthCheckRequest\x1a\x1b.health.HealthCheckResponse0\x01B5Z3github.com/eliezerraj/go-grpc-proto/protogen/healthb\x06proto3"

var file_proto_health_health_service_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),  // 0: health.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 1: health.HealthCheckResponse
}
var file_proto_health_health_service_proto_depIdxs = []int32{
	0, // 0: health.Health.Check:input_type -> health.HealthCheckRequest
	0, // 1: health.Health.Watch:input_type -> health.HealthCheckRequest
	1, // 2: health.Health.Check:output_type -> health.HealthCheckResponse
	1, // 3: health.Health.Watch:output_type -> health.HealthCheckResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_health_health_service_proto_init() }
func file_proto_health_health_service_proto_init() {
	if File_proto_health_health_service_proto != nil {
		return
	}
	file_proto_health_health_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_health_health_service_proto_rawDesc), len(file_proto_health_health_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_health_health_service_proto_goTypes,
		DependencyIndexes: file_proto_health_health_service_proto_depIdxs,
	}.Build()
	File_proto_health_health_service_proto = out.File
	file_proto_health_health_service_proto_goTypes = nil
	file_proto_health_health_service_proto_depIdxs = nil
}
